# 
policy_path: "{LEGGED_GYM_ROOT_DIR}/deploy/pre_train/a1/a1_perception.pt"
xml_path: "{LEGGED_GYM_ROOT_DIR}/resources/robots/a1/xml/a1.xml"

# Total simulation time
simulation_duration: 60.0
# Simulation time step
simulation_dt: 0.005
# Controller update frequency (meets the requirement of simulation_dt * controll_decimation=0.02; 50Hz)
control_decimation: 4

kps: [40, 40, 40,
      40, 40, 40,
      40, 40, 40,
      40, 40, 40]
kds: [1.0, 1.0, 1.0,
      1.0, 1.0, 1.0,
      1.0, 1.0, 1.0,
      1.0, 1.0, 1.0]

# kps: [20, 20, 20,
#       20, 20, 20,
#       20, 20, 20,
#       20, 20, 20]
# kds: [0.5, 0.5, 0.5,
#       0.5, 0.5, 0.5,
#       0.5, 0.5, 0.5,
#       0.5, 0.5, 0.5]

default_angles: [ 0.1000, 0.8000, -1.5000, # FR_hip_joint, FR_thigh_joint, FR_calf_joint
                  -0.1000, 0.8000, -1.5000,  # RL_hip_joint, FL_thigh_joint, FL_calf_joint
                  0.1000, 1.0000, -1.5000, # RR_hip_joint, RR_thigh_joint, RR_calf_joint
                  -0.1000, 1.0000, -1.5000]  # RL_hip_joint, RL_thigh_joint, RL_calf_joint

ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25
cmd_scale: [2.0, 2.0, 0.25]
num_actions: 12
num_obs: 162  # 45+117
num_obs_frame: 6
hip_reduction: 1.0
cmd_init: [0.6, 0, 0]